export const images = {
  background: require('./images/kinddsuspiccoonbrdbg.png'),
  loaderIcon: require('./images/loaderIco.png'),
  androidIcon: require('./images/andricon.png'),
  tabCases: require('./images/kinddsuspiccoonbrdicncasecards.png'),
  tabStories: require('./images/kinddsuspiccoonbrdicnstories.png'),
  tabParty: require('./images/kinddsuspiccoonbrdicnparty.png'),
  tabCiphers: require('./images/kinddsuspiccoonbrdicnciphers.png'),
  tabSettings: require('./images/kinddsuspiccoonbrdicnsettings.png'),
  onboardingHero1: require('./images/kinddsuspiccoonbrdhero1.png'),
  onboardingHero2: require('./images/kinddsuspiccoonbrdhero2.png'),
  onboardingHero3: require('./images/kinddsuspiccoonbrdhero3.png'),
  onboardingHero4: require('./images/kinddsuspiccoonbrdhero4.png'),
  pause: require('./images/pause.png'),
  categoryPickerRing: require('./images/whll.png'),
  result: require('./images/result.png'),
  savedIcon: require('./images/savedic.png'),
  correctLabel: require('./images/correct_label.png'),
  wrongLabel: require('./images/wrong_label.png'),
} as const;
